### ISSUE TITLE
Limpiar código

### ISSUE THREAD

**Issue by GuiselleZP** [IngenioUN/front_end#12]
Eliminar archivos inecesarios.

**Comment by vhuepad** [comment]
Solucionar problemas de SonarCloud

**Comment by GuiselleZP** [comment]
- Dejar las tabulaciones de tamaño 2 en todos los archivos.
- Cambiar el idioma en el que se está trabajando
- Eliminar archivos y solucionar problemas que generen conflictos en SonarCloud
- Eliminar archivos que no se utilizan (no se integran con el back)
